### ISSUE TITLE
"NSE:NIFTYNXT50-INDEX" symbol not found 

### ISSUE THREAD

**Issue by varshith264** [FyersDev/Fyers-Trading-APIs-Sample-Code#25]
Getting -300 error when trying to subscribe to "NSE:NIFTYNXT50-INDEX" symbol using fyers java sdk.
Detailed error:
2024-11-30 16:29:08 INFO  FyersSocketHandler:64 - On Error: {"code":-300,"s":"error","invalid_symbols":"NSE:NIFTYNXT50-INDEX","type":"if","message":"Please provide a valid symbol"}

Note:
"NSE:NIFTYNXT50-INDEX" is a valid symbol for
<img width="866" alt="Screenshot 2024-11-30 at 4 34 28 PM" src="https://github.com/user-attachments/assets/1883134a-6809-4709-b240-53f404f261da">

**Comment by SHIVANIUM-GIT** [comment]
```bash 

data = {"symbol": "NSE:NIFTYNXT50-INDEX", "resolution": "1", "date_format": "1",
        "range_from": "2023-01-17", "range_to": "2023-01-17", "cont_flag": "1"}

print(fyers.history(data))
```

note: I am using python and  'code': 200, 'message': '', 's': 'ok'

**Comment by varshith264** [comment]
Hi @SHIVANIUM-GIT ,
history data api is working fine with "NSE:NIFTYNXT50-INDEX", but subscribing to live data feed for "NSE:NIFTYNXT50-INDEX" is causing the error

FyersSocket fyersSocket = new FyersSocket(3);
fyersSocket.SubscribeData(List.of("NSE:NIFTYNXT50-INDEX"));

{"code":-300,"s":"error","invalid_symbols":"NSE:NIFTYNXT50-INDEX","type":"if","message":"Please provide a valid symbol"}

**Comment by varshith264** [comment]
"NSE:NIFTYNEXT50-INDEX" is the correct symbol for subscribing to live data
